### ISSUE TITLE
Is there any way for KSCrash or plcrashreporter to catch exceptions in KMM?

### ISSUE THREAD

**Issue by fenglh** [touchlab/CrashKiOS#13]
Is there any way for KSCrash or plcrashreporter to catch exceptions in KMM? I know that CrashKiOS can be used to catch exceptions, but we are not allowed to report exception messages separately.

**Comment by kpgalligan** [comment]
> Is there any way for KSCrash or plcrashreporter to catch exceptions in KMM?

Maybe. You'll need to be able to submit a supplemental report with the stack trace. That means you'll need to figure out if either of those libraries are capable of that first, then implement it.

> I  know that CrashKiOS can be used to catch exceptions, but we are not allowed to report exception messages separately.

I don't know what you're asking here, TBH.

Sorry for delay, btw. We've improved our internal processes and tooling, so we should be on top of issues going forward :)
