### ISSUE TITLE
Creating a git tag for 0.3.2 release

### ISSUE THREAD

**Issue by vanniktech** [touchlab/CrashKiOS#15]
Would you mind creating the git tag for the 0.3.2 release?

In a project of mine I'm required to have license links to the libraries I'm using with the designated version and that only works as long as it's tagged.

**Comment by vanniktech** [comment]
cc @russhwolf as you created the new version

**Comment by russhwolf** [comment]
Sorry to miss this! 0.3.2 is now tagged (as well as the more recent 0.4.0)
