### ISSUE TITLE
Unable to locate dsyms for freelytics.flowredux 

### ISSUE THREAD

**Issue by nishantgupta2501** [touchlab/CrashKiOS#18]
We're using flowredux in our KMM shared module and when I integrated crashkios exporting KMM framework with isStatic = true, getting bunch of compilation warnings "(x86_64)  could not find object file symbol for symbol _kfun:com.freeletics.flowredux#reduxStore__at__kotlinx.coroutines.flow.Flow<0:0>(kotlin.Function0<0:1>;kotlin.collections.Iterable<kotlin.Function2<kotlinx.coroutines.flow.Flow<0:0>,kotlin.Function0<0:1>,kotlinx.coroutines.flow.Flow<0:0>>>;com.freeletics.flowredux.FlowReduxLogger?;kotlin.Function2<0:1,0:0,0:1>){0§<kotlin.Any"

Any help is appreciated

**Comment by kpgalligan** [comment]
No idea, but this is old anyway (sorry). Closing.
