### ISSUE TITLE
Integration Issue

### ISSUE THREAD

**Issue by IlyasNN** [touchlab/CrashKiOS#20]
Can't integrate CrashKios

![photo_2021-12-16 23 35 57](https://user-images.githubusercontent.com/50013971/146445586-41218286-4fa3-44b8-99b3-46cfd23ae27d.jpeg)
![photo_2021-12-16 23 36 05](https://user-images.githubusercontent.com/50013971/146445613-da95f064-650e-4c51-9a27-1d91e990070a.jpeg)

Dependency is not visible in iosMain. Can't find solution...

May be because of Mac M1

**Comment by kpgalligan** [comment]
Maybe? Many ide related import issues that aren't library-specific. If this is still an issues, update and re-open.
