### ISSUE TITLE
How to report crashes using the new Firebase Crashlytics?

### ISSUE THREAD

**Issue by Thomas-Vos** [touchlab/CrashKiOS#3]
In the new version of Firebase Crashlytics the function `recordCustomExceptionName:reason:frameArray:` is replaced by `recordError`.

See the following: https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=ios#recordcustomexceptionnamereasonframearray_is_replaced_by_recorderror

The alternative appears to be one of the following:

- [record(error:)](https://firebase.google.com/docs/reference/swift/firebasecrashlytics/api/reference/Classes/Crashlytics#recorderror:)
- [record(exceptionModel:)](https://firebase.google.com/docs/reference/swift/firebasecrashlytics/api/reference/Classes/Crashlytics#recordexceptionmodel:)

The [ExceptionModel can be created using a name, reason, and stackTrace](https://firebase.google.com/docs/reference/swift/firebasecrashlytics/api/reference/Classes/ExceptionModel). This looks like the way to go but I cannot find a way to create a [StackFrame](https://firebase.google.com/docs/reference/swift/firebasecrashlytics/api/reference/Classes/StackFrame) using an address. The StackFrame only has a constructor for symbol, file, and line. Any ideas how to report the exception to Firebase now?

**Comment by Thomas-Vos** [comment]
Related: https://github.com/firebase/firebase-ios-sdk/issues/5182

**Comment by jiehu5114** [comment]
mark

**Comment by Thomas-Vos** [comment]
Firebase 6.32.0 fixes this issue:
```swift
class CrashlyticsCrashHandler: CrashkiosCrashHandler {
    override func crashParts(
        addresses: [KotlinLong],
        exceptionType: String,
        message: String
    ) {
        let exceptionModel = ExceptionModel(name: exceptionType, reason: message)
        exceptionModel.stackTrace = addresses.map {
            StackFrame(address: UInt(truncating: $0))
        }
        Crashlytics.crashlytics().record(exceptionModel: exceptionModel)
    }
}
```

**Comment by matteobianchi3** [comment]
I've tried it but I get a "(Missing)" label instead of the correct "file + line" label related to an exception raised from the Kotlin/Native "shared" framework, and I'm quite confidente that the related dSYMs have been correctly uploaded to Firebase Crashlytics; any idea?

**Comment by Thomas-Vos** [comment]
@matteobianchi3 Did you upload the dSYMs from App Store Connect as well (if you are using bitcode)?

**Comment by matteobianchi3** [comment]
I have bitcode disabled.
I've now added this script at the end of the build phases
```
# validation
"${PODS_ROOT}/FirebaseCrashlytics/upload-symbols" -val -gsp "${PROJECT_DIR}/${PROJECT}/GoogleService-Info.plist" -p ios -- "${DWARF_DSYM_FOLDER_PATH}"

# background upload
"${PODS_ROOT}/FirebaseCrashlytics/upload-symbols" -gsp "${PROJECT_DIR}/${PROJECT}/GoogleService-Info.plist" -p ios -- "${DWARF_DSYM_FOLDER_PATH}" > /dev/null 2>&1 &
```
and Crashlytics seems to be able to symbolicate custom Kotlin exception reports.

Using the simple "official" Crashlytics script `"${PODS_ROOT}/FirebaseCrashlytics/run"` doesn't work since it only uploads the app's dSYM and not the framework's one.

Does all of this make sense to you?

**Comment by Thomas-Vos** [comment]
Looks all right I think, it is similar to what is mentioned in the CrashKiOS readme: https://github.com/touchlab/CrashKiOS#upload-dsyms-to-crashlytics

I have the script that is mentioned in the readme in my project as well.

**Comment by kpgalligan** [comment]
closing this for now. We have explicit support in Kermit for adding Crashllytics. You don't have to use it but can see how we do it there.

https://github.com/touchlab/Kermit
