### ISSUE TITLE
Support `setUserId` call in `CrashlyticsKotlin`

### ISSUE THREAD

**Issue by rocketraman** [touchlab/CrashKiOS#43]
The `setUserId` call is not exposed in `CrashlyticsKotlin`. See https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#set-user-ids and https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios#set-user-ids.

**Comment by LuuNguyen0811** [comment]
same issue
