### ISSUE TITLE
Invalid Certificate

### ISSUE THREAD

**Issue by scott-kajutech** [touchlab/CrashKiOS#72]
Hello, there seems to be an issue with the certificate where your release builds are being hosted: 

![IMG_7315](https://github.com/user-attachments/assets/3d453823-e013-4c04-b71d-17826a4ed775)

**Comment by samhill303** [comment]
We shouldn't be using jfrog, can you please provide more detail about how this relates to CrashKiOS?

**Comment by scott-kajutech** [comment]
Gradle can’t download CrashKiOS as a dependency due to the invalid certificate. This is the location it attempts to download from:

https://kotlin.bintray.com/kotlinx/co/touchlab/crashkios/0.9.0/crashkios-0.9.0.pom
