### ISSUE TITLE
Is it possible to have only one crash report per exception

### ISSUE THREAD

**Issue by romanandreyvich** [touchlab/CrashKiOS#9]
For now every exception happened in common code is presented in Crashlytics as two crash reports. One fatal crash and one non-fatal. 
Is it possible to have only one crash report with readable stack trace?

**Comment by micHar** [comment]
I was wondering the same thing, but from the Crashlytics docs it seems that there's no option to alter the original fatal stack trace or report a fatal exception: https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios#customize-stack-traces

**Comment by kpgalligan** [comment]
Not possible. Long rambling post about it: https://www.kgalligan.com/crash-reporting-and-kmp/. Crashlytics would need to change the client. It is open source, so in theory a community member could, but it would be a lot of maintenance.
